import { Machine } from "@mygym/specs";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useCallback, useState } from "react";
import styles from "../styles/Home.module.css";
import { getApiAgent } from "../src/api-agent";

const Home: NextPage = () => {
  const [machines, setMachines] = useState<Machine[]>([]);
  const [offset, setOffset] = useState(0);
  const getMore = useCallback(() => {
    (async () => {
      const res = await getApiAgent().listMachines({ offset, limit: 3 });
      setMachines([...machines, ...res]);
      setOffset(offset + res.length);
    })();
  }, [machines, offset]);
  return (
    <div className={styles.container}>
      <Head>
        <title>MyGym</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to MyGym</h1>

        <button onClick={getMore}>load more</button>
        <div className={styles.divTable}>
          <div className={styles.headRow}>
            <div className={styles.divCell}>ID</div>
            <div className={styles.divCell}>Name</div>
            <div className={styles.divCell}>Tag</div>
          </div>
          {machines.map((m) => (
            <div key={m.id} className={styles.divRow}>
              <div className={styles.divCell}>{m.id}</div>
              <div className={styles.divCell}>{m.name}</div>
              <div className={styles.divCell}>{m.tag}</div>
            </div>
          ))}
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
