openapi: "3.0.0"
info:
  version: 1.0.0
  title: MyGym Machines
  license:
    name: MIT
paths:
  /:
    get:
      summary: Health Check
      operationId: getMyHealth
      responses:
        '200':
          description: Health Check Answer
          content:
            application/json:    
              schema:
                type: string
  /machines:
    get:
      summary: List all machines
      operationId: listMachines
      tags:
        - machines
      parameters:
        - name: offset
          in: query
          description: How many items to skip. Use for pagination
          required: false
          schema:
            type: integer
            format: int32
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of machines
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Machines"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a machine
      operationId: createMachines
      tags:
        - machines
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /machines/{machineId}:
    get:
      summary: Info for a specific machine
      operationId: showMachineById
      tags:
        - machines
      parameters:
        - name: machineId
          in: path
          required: true
          description: The id of the machine to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Machine"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Machine:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Machines:
      type: array
      items:
        $ref: "#/components/schemas/Machine"
    Error:
      type: object
      required:
        - code
        - name
      properties:
        code:
          type: integer
          format: int32
        name:
          type: string
