# NOTE: https://hoshinotsuyoshi.com/post/merge-ff/
name: fast-forwardのマージ

on:
  pull_request:
    types: [labeled]
    branches:
      - main

jobs:
  pull_request_merge:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ startsWith(github.event.label.name, 'merge-ff') }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check for PR approval
      id: check_approval
      uses: actions/github-script@v5
      with:
        script: |
          const { data: reviews } = await github.rest.pulls.listReviews({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
          });
          const approved = reviews.some(review => review.state === 'APPROVED');
          if (!approved) {
            core.setFailed('PRがまだ承認されていない。');
          } else {
            console.log('PRが承認された');
          }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Fast Forward Merge
      uses: robotology/gh-action-nightly-merge@v1.5.0
      with:
        stable_branch: ${{ github.event.pull_request.head.ref }}
        development_branch: ${{ github.event.pull_request.base.ref }}

        # NOTE: fast forwardでマージするにはこの2つが必要
        allow_ff: true
        ff_only: true

        # NOTE: robotology/gh-action-nightly-mergeの実装の都合上、
        # プライベートリポジトリの場合はallow_forks: trueでないと動かないかもしれません
        allow_forks: false

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
